USE League_Gamble;
CREATE TABLE IF NOT EXISTS  `fl_group`
(
    `id`                int auto_increment,
    `user1_name`           varchar(255),
    `user2_name`           varchar(255),
    `user3_name`           varchar(255),
    `user4_name`           varchar(255),
    `user5_name`           varchar(255),
    `user6_name`           varchar(255),
    `user7_name`           varchar(255),
    `user8_name`           varchar(255),
    `user9_name`           varchar(255),
    `user10_name`           varchar(255),
    `user11_name`           varchar(255),
    `user12_name`           varchar(255),
    `created`           timestamp default current_timestamp,
    `modified`          timestamp default current_timestamp on update current_timestamp,
    PRIMARY KEY (`id`),
    FOREIGN KEY (`user1_name`) REFERENCES Users(`username`),
    FOREIGN KEY (`user2_name`) REFERENCES Users(`username`),
    FOREIGN KEY (`user3_name`) REFERENCES Users(`username`),
    FOREIGN KEY (`user4_name`) REFERENCES Users(`username`),
    FOREIGN KEY (`user5_name`) REFERENCES Users(`username`),
    FOREIGN KEY (`user6_name`) REFERENCES Users(`username`),
    FOREIGN KEY (`user7_name`) REFERENCES Users(`username`),
    FOREIGN KEY (`user8_name`) REFERENCES Users(`username`),
    FOREIGN KEY (`user9_name`) REFERENCES Users(`username`),
    FOREIGN KEY (`user10_name`) REFERENCES Users(`username`),
    FOREIGN KEY (`user11_name`) REFERENCES Users(`username`),
    FOREIGN KEY (`user12_name`) REFERENCES Users(`username`)
)
